-- Add query-level collector run tracking for supplement discovery.
-- Expected impact before first execution:
--   - Creates public.collection_runs if it does not already exist.
--   - Adds missing columns/indexes if a partial table exists.
-- Expected impact after successful execution / rerun:
--   - 0 data rows changed.
--   - DDL is idempotent.

BEGIN;

CREATE TABLE IF NOT EXISTS public.collection_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id uuid NOT NULL,
  mode text NOT NULL,
  source text NOT NULL,
  phase integer,
  region_code text,
  cell_id text,
  query text NOT NULL,
  keyword text,
  query_family text,
  status text NOT NULL,
  result_count integer NOT NULL DEFAULT 0,
  unique_count integer NOT NULL DEFAULT 0,
  total_count integer,
  pageable_count integer,
  is_saturated boolean,
  external_ids text[] NOT NULL DEFAULT '{}',
  error_message text,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

ALTER TABLE public.collection_runs
  ADD COLUMN IF NOT EXISTS run_id uuid,
  ADD COLUMN IF NOT EXISTS mode text,
  ADD COLUMN IF NOT EXISTS source text,
  ADD COLUMN IF NOT EXISTS phase integer,
  ADD COLUMN IF NOT EXISTS region_code text,
  ADD COLUMN IF NOT EXISTS cell_id text,
  ADD COLUMN IF NOT EXISTS query text,
  ADD COLUMN IF NOT EXISTS keyword text,
  ADD COLUMN IF NOT EXISTS query_family text,
  ADD COLUMN IF NOT EXISTS status text,
  ADD COLUMN IF NOT EXISTS result_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS unique_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_count integer,
  ADD COLUMN IF NOT EXISTS pageable_count integer,
  ADD COLUMN IF NOT EXISTS is_saturated boolean,
  ADD COLUMN IF NOT EXISTS external_ids text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS error_message text,
  ADD COLUMN IF NOT EXISTS started_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS completed_at timestamptz;

ALTER TABLE public.collection_runs
  ALTER COLUMN run_id SET NOT NULL,
  ALTER COLUMN mode SET NOT NULL,
  ALTER COLUMN source SET NOT NULL,
  ALTER COLUMN query SET NOT NULL,
  ALTER COLUMN status SET NOT NULL,
  ALTER COLUMN result_count SET DEFAULT 0,
  ALTER COLUMN result_count SET NOT NULL,
  ALTER COLUMN unique_count SET DEFAULT 0,
  ALTER COLUMN unique_count SET NOT NULL,
  ALTER COLUMN external_ids SET DEFAULT '{}',
  ALTER COLUMN external_ids SET NOT NULL,
  ALTER COLUMN started_at SET DEFAULT now(),
  ALTER COLUMN started_at SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'collection_runs_source_check'
      AND conrelid = 'public.collection_runs'::regclass
  ) THEN
    ALTER TABLE public.collection_runs
      ADD CONSTRAINT collection_runs_source_check
      CHECK (source IN ('kakao', 'google'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'collection_runs_query_family_check'
      AND conrelid = 'public.collection_runs'::regclass
  ) THEN
    ALTER TABLE public.collection_runs
      ADD CONSTRAINT collection_runs_query_family_check
      CHECK (query_family IS NULL OR query_family IN ('direct', 'adjacent'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'collection_runs_status_check'
      AND conrelid = 'public.collection_runs'::regclass
  ) THEN
    ALTER TABLE public.collection_runs
      ADD CONSTRAINT collection_runs_status_check
      CHECK (status IN ('success', 'failure', 'skipped', 'dry_run'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS collection_runs_run_id_idx
  ON public.collection_runs (run_id);

CREATE INDEX IF NOT EXISTS collection_runs_mode_source_completed_idx
  ON public.collection_runs (mode, source, completed_at DESC);

CREATE INDEX IF NOT EXISTS collection_runs_region_query_idx
  ON public.collection_runs (mode, source, phase, region_code, cell_id, query);

ALTER TABLE public.collection_runs ENABLE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload schema';

COMMIT;
